apiVersion: batch/v1
kind: Job
metadata:
  name: kratos-migrate
  namespace: secure
  annotations:
    argocd.argoproj.io/sync-wave: "55"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  # Автоматически удалить Job через 5 минут после завершения (успешного или неуспешного)
  ttlSecondsAfterFinished: 300
  # Ограничить время выполнения миграции 10 минутами
  activeDeadlineSeconds: 600
  backoffLimit: 2  # Уменьшено с 3 до 2, чтобы быстрее выявить проблемы
  template:
    metadata:
      annotations:
        # Vault Agent Injector аннотации для чтения секретов из Vault
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-kratos-db: "kv/data/archpad/demo/ory/kratos/db"
        vault.hashicorp.com/agent-inject-secret-kratos-secret: "kv/data/archpad/demo/ory/kratos/secret"
        vault.hashicorp.com/agent-inject-secret-kratos-other: "kv/data/archpad/demo/ory/kratos/other"
        vault.hashicorp.com/agent-inject-secret-postgres-connect: "kv/data/archpad/demo/postgres/connect"
        vault.hashicorp.com/agent-inject-template-kratos: |
          {{- $kratosDb := secret "kv/data/archpad/demo/ory/kratos/db" }}
          {{- $kratosSecret := secret "kv/data/archpad/demo/ory/kratos/secret" }}
          {{- $kratosOther := secret "kv/data/archpad/demo/ory/kratos/other" }}
          {{- $postgresConnect := secret "kv/data/archpad/demo/postgres/connect" }}
          # Формируем DSN из компонентов
          {{- $password := $kratosDb.Data.data.KRATOS_DB_PASSWORD | urlquery }}
          {{- $pgHost := $postgresConnect.Data.data.POSTGRES_HOST }}
          {{- $pgPort := $postgresConnect.Data.data.POSTGRES_PORT }}
          export DSN="postgres://{{ $kratosDb.Data.data.KRATOS_DB_USER }}:{{ $password }}@{{ $pgHost }}:{{ $pgPort }}/{{ $kratosDb.Data.data.KRATOS_DB }}?sslmode=disable&max_conns=20&max_idle_conns=4"
          export KRATOS_SECRET="{{ $kratosSecret.Data.data.KRATOS_SECRET }}"
          export SMTP_CONNECTION_URI="{{ $kratosOther.Data.data.SMTP_CONNECTION_URI }}"
          export SMTP_FROM_ADDRESS="{{ $kratosOther.Data.data.SMTP_FROM_ADDRESS }}"
        vault.hashicorp.com/role: "secure"
    spec:
      serviceAccountName: kratos
      restartPolicy: Never
      containers:
        - name: kratos-migrate
          image: oryd/kratos:v25.4.0
          command: ["sh", "-c"]
          args:
            - |
              set -euo pipefail
              
              # Ждем, пока Vault Agent Injector создаст файлы секретов
              echo "Waiting for Vault secrets..."
              max_wait=60
              waited=0
              # В этом Job переменные окружения рендерятся в файл /vault/secrets/kratos
              # (см. vault.hashicorp.com/agent-inject-template-kratos). Файл /vault/secrets/kratos-db
              # создаётся Vault Agent'ом по дефолтному шаблону и НЕ является shell-скриптом.
              while [ ! -f /vault/secrets/kratos ] && [ $waited -lt $max_wait ]; do
                echo "Waiting for /vault/secrets/kratos... (${waited}s/${max_wait}s)"
                sleep 2
                waited=$((waited+2))
              done
              
              if [ ! -f /vault/secrets/kratos ]; then
                echo "ERROR: /vault/secrets/kratos not found after ${max_wait}s"
                exit 1
              fi
              
              # Загружаем секреты
              echo "Loading secrets from Vault..."
              source /vault/secrets/kratos || { echo "ERROR: Failed to load kratos secrets"; exit 1; }
              
              if [ -f /vault/secrets/kratos-secret ]; then
                source /vault/secrets/kratos-secret || echo "WARNING: Failed to load kratos-secret"
              fi
              
              if [ -f /vault/secrets/kratos-other ]; then
                source /vault/secrets/kratos-other || echo "WARNING: Failed to load kratos-other"
              fi
              
              # Проверяем наличие обязательных переменных
              if [ -z "${DSN:-}" ]; then
                echo "ERROR: DSN is not set"
                exit 1
              fi
              
              echo "DSN configured: postgres://${DSN#postgres://}" | sed 's/:[^@]*@/:***@/g'
              
              # Проверяем доступность конфиг-файла
              if [ ! -f /etc/config/kratos.yml ]; then
                echo "ERROR: Config file /etc/config/kratos.yml not found"
                exit 1
              fi
              
              # Выполняем миграцию
              echo "Running Kratos database migration..."
              kratos migrate sql -e --yes -c /etc/config/kratos.yml
              
              echo "Migration completed successfully!"
          volumeMounts:
            - name: config
              mountPath: /etc/config/kratos.yml
              subPath: kratos.yml
            - name: identity-schema
              mountPath: /etc/config/kratos/identities/default.schema.json
              subPath: default.schema.json
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: kratos
        - name: identity-schema
          configMap:
            name: kratos-identity-schema
