version: v25.4.0

dsn: ${DSN}

log:
  level: info
  leak_sensitive_values: true

serve:
  cookies:
    same_site_mode: Lax
  public:
    host: 0.0.0.0
    port: 4444
      cors:
      enabled: true
      allowed_origins:
        - https://portal.192-168-1-119.sslip.io
        - https://kratos.192-168-1-119.sslip.io
        - https://hydra.192-168-1-119.sslip.io
        - https://api.192-168-1-119.sslip.io
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
        - Cookie
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    host: 0.0.0.0
    port: 4445
    cors:
      enabled: true
      allowed_origins:
        - https://portal.192-168-1-119.sslip.io
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
        - Cookie


secrets:
  system:
    # IMPORTANT: must stay stable when using a persistent SQL database.
    # Set it in your root `.env` as SECRETS_SYSTEM=... (or use the default below for fresh dev DBs).
    - ${SECRETS_SYSTEM:-nApRkoCIUm7lLYvGCvAmT8jgnqk0LhDAXlBaWVIngEL}

urls:
  self:
    issuer: https://hydra.192-168-1-119.sslip.io
  login: https://portal.192-168-1-119.sslip.io/hydra/login
  consent: https://portal.192-168-1-119.sslip.io/hydra/consent
  logout: https://portal.192-168-1-119.sslip.io/logout
  error: https://portal.192-168-1-119.sslip.io/error
  post_logout_redirect: https://portal.192-168-1-119.sslip.io/

strategies:
  access_token: opaque
  scope: exact

oauth2:
  expose_internal_errors: true
  session:
    encrypt_at_rest: true
  hashers:
    algorithm: pbkdf2
    pbkdf2:
      iterations: 25000

ttl:
  login_consent_request: 10m
  access_token: 15m
  refresh_token: 720h
  id_token: 15m
  auth_code: 10m
