dsn: ${DSN}

serve:
  public:
    base_url: https://kratos.192-168-1-119.sslip.io
    port: 4433
    cors:
      enabled: true
      allowed_origins:
        - https://portal.192-168-1-119.sslip.io
        - https://kratos.192-168-1-119.sslip.io
        - https://hydra.192-168-1-119.sslip.io
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie

  admin:
    base_url: http://kratos:4434/
    host: 0.0.0.0
    port: 4434

selfservice:
  default_browser_return_url: https://portal.192-168-1-119.sslip.io/
  allowed_return_urls:
    - https://portal.192-168-1-119.sslip.io/
  methods:
    password:
      enabled: true
  flows:
    login:
      ui_url: https://portal.192-168-1-119.sslip.io/sign-in
      lifespan: 1h
      style: unified
    registration:
      ui_url: https://portal.192-168-1-119.sslip.io/sign-up
      enabled: true
      enable_legacy_one_step: false
      lifespan: 1h
      style: unified
    settings:
      ui_url: https://portal.192-168-1-119.sslip.io/settings
      lifespan: 1h
      privileged_session_max_age: 1h
      required_aal: highest_available
    recovery:
      enabled: true
      lifespan: 1h
      notify_unknown_recipients: false
      use: code
      ui_url: https://portal.192-168-1-119.sslip.io/recovery
    verification:
      ui_url: https://portal.192-168-1-119.sslip.io/verify
      enabled: true
      lifespan: 1h
      notify_unknown_recipients: false
      use: code

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identities/default.schema.json

cookies:
  domain: .192-168-1-119.sslip.io
  path: /
  same_site: Lax
  secure: "auto"

log:
  level: info
  format: json

secrets:
  default:
    - ReMUeeq8tyEmmAHFBUiKtzkEmX9aMZr7

session:
  lifespan: 720h

# Email delivery (verification / recovery codes, etc.)
courier:
  smtp:
    # Mailpit SMTP (no auth). Query params are understood by Kratos' SMTP URI parser.
    connection_uri: smtp://mailpit:1025/?disable_starttls=true
    from_address: no-reply@archpad.local
