apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "60"
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP

