apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd-image-updater.argoproj.io/image-list: auth-service=archpad-cr.registry.twcstorage.ru/archpad/auth-service
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/auth-service.update-strategy: latest
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  source:
    repoURL: https://gitlab.com/zs-archipad/archpad.git
    targetRevision: main
    path: infra/timeweb/10-gitops/apps/backend/auth-service
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

