# PersistentVolume для pgAdmin на основе hostPath
# PersistentVolume - cluster-scoped ресурс, не имеет namespace
# Этот файл управляется через корневой kustomization.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-data-pv
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /var/lib/pgadmin-data
    type: DirectoryOrCreate
