# Secret с credentials для pgAdmin
# PGADMIN_DEFAULT_EMAIL вынесен в Vault: /v1/kv/data/archpad/demo/pgadmin (ключ: PGADMIN_ADMIN_USER)
# TODO: В будущем можно полностью интегрировать с Vault через ArgoCD Vault Plugin
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-credentials
  namespace: pgadmin
  annotations:
    argocd.argoproj.io/sync-wave: "20"
type: Opaque
stringData:
  PGADMIN_DEFAULT_PASSWORD: Hpv4hHuoTFRYLGJukwr74ND9VeOLHv
