# Secret с credentials для pgAdmin
# TODO: В будущем можно интегрировать с Vault через ArgoCD Vault Plugin
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-credentials
  namespace: pgadmin
  annotations:
    argocd.argoproj.io/sync-wave: "20"
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: admin@archpad.pro
  PGADMIN_DEFAULT_PASSWORD: Hpv4hHuoTFRYLGJukwr74ND9VeOLHv
