apiVersion: batch/v1
kind: Job
metadata:
  name: pgadmin-copy-tls-secret
  namespace: pgadmin
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      annotations:
        argocd.argoproj.io/hook-weight: "0"
    spec:
      serviceAccountName: default
      restartPolicy: Never
      containers:
        - name: copy-secret
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - |
              set -e
              echo "Checking if wildcard-archpad-pro-tls exists in namespace pgadmin..."

              if kubectl get secret wildcard-archpad-pro-tls -n pgadmin >/dev/null 2>&1; then
                echo "✓ Secret wildcard-archpad-pro-tls already exists in namespace pgadmin"
                exit 0
              fi

              echo "Secret not found in pgadmin namespace. Searching for source secret..."

              SOURCE_NS=""
              for ns in pgadmin platform traefik argocd; do
                if kubectl get secret wildcard-archpad-pro-tls -n "$ns" >/dev/null 2>&1; then
                  SOURCE_NS="$ns"
                  echo "Found secret in namespace: $ns"
                  break
                else
                  echo "Secret not found in namespace: $ns (may not have permissions to read)"
                fi
              done

              if [ -z "$SOURCE_NS" ] || [ "$SOURCE_NS" = "pgadmin" ]; then
                echo "WARNING: Source secret wildcard-archpad-pro-tls not found or not accessible."
                echo "This is not critical - pgadmin will work once the secret is available."
                exit 0
              fi

              echo "Copying secret from namespace $SOURCE_NS to pgadmin..."
              kubectl get secret wildcard-archpad-pro-tls -n "$SOURCE_NS" -o yaml | \
                sed "s/namespace: $SOURCE_NS/namespace: pgadmin/" | \
                sed '/resourceVersion:/d' | \
                sed '/uid:/d' | \
                sed '/creationTimestamp:/d' | \
                kubectl apply -f -

              echo "✓ Successfully copied wildcard-archpad-pro-tls to namespace pgadmin"
  backoffLimit: 3
