# Middleware для редиректа HTTP → HTTPS для pgAdmin
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: pgadmin
  annotations:
    argocd.argoproj.io/sync-wave: "55"
spec:
  redirectScheme:
    scheme: https
    permanent: true
