apiVersion: batch/v1
kind: Job
metadata:
  name: mailpit-copy-tls-secret
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      annotations:
        argocd.argoproj.io/hook-weight: "0"
    spec:
      serviceAccountName: default
      restartPolicy: Never
      containers:
        - name: copy-secret
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - |
              set -e
              echo "Checking if wildcard-archpad-pro-tls exists in namespace platform..."
              
              if kubectl get secret wildcard-archpad-pro-tls -n platform >/dev/null 2>&1; then
                echo "✓ Secret wildcard-archpad-pro-tls already exists in namespace platform"
                exit 0
              fi
              
              echo "Secret not found in platform namespace. Searching for source secret..."
              
              # Ищем secret в разных namespace'ах (в порядке приоритета)
              # Проверяем сначала platform (на случай, если проверка выше не сработала)
              # Затем traefik, затем argocd
              SOURCE_NS=""
              for ns in platform traefik argocd; do
                if kubectl get secret wildcard-archpad-pro-tls -n "$ns" >/dev/null 2>&1; then
                  SOURCE_NS="$ns"
                  echo "Found secret in namespace: $ns"
                  break
                else
                  echo "Secret not found in namespace: $ns (may not have permissions to read)"
                fi
              done
              
              if [ -z "$SOURCE_NS" ]; then
                echo "WARNING: Secret wildcard-archpad-pro-tls not found or not accessible in any namespace"
                echo "This may be due to RBAC restrictions or the certificate not being issued yet."
                echo "If the secret exists in namespace argocd, you can manually copy it:"
                echo "  kubectl get secret wildcard-archpad-pro-tls -n argocd -o yaml | \\"
                echo "    sed 's/namespace: argocd/namespace: platform/' | \\"
                echo "    sed '/resourceVersion:/d' | sed '/uid:/d' | sed '/creationTimestamp:/d' | \\"
                echo "    kubectl apply -f -"
                echo ""
                echo "This is not critical - Mailpit will work once the secret is available."
                exit 0  # Не считаем это ошибкой
              fi
              
              if [ "$SOURCE_NS" = "platform" ]; then
                echo "✓ Secret already exists in platform namespace"
                exit 0
              fi
              
              echo "Copying secret from namespace $SOURCE_NS to platform..."
              kubectl get secret wildcard-archpad-pro-tls -n "$SOURCE_NS" -o yaml | \
                sed "s/namespace: $SOURCE_NS/namespace: platform/" | \
                sed '/resourceVersion:/d' | \
                sed '/uid:/d' | \
                sed '/creationTimestamp:/d' | \
                kubectl apply -f -
              
              echo "✓ Successfully copied wildcard-archpad-pro-tls to namespace platform"
      backoffLimit: 3
