apiVersion: batch/v1
kind: Job
metadata:
  name: mailpit-copy-tls-secret
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      annotations:
        argocd.argoproj.io/hook-weight: "0"
    spec:
      serviceAccountName: default
      restartPolicy: Never
      containers:
        - name: copy-secret
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - |
              set -eu
              echo "Checking if wildcard-archpad-pro-tls exists in namespace platform..."
              
              if kubectl get secret wildcard-archpad-pro-tls -n platform >/dev/null 2>&1; then
                echo "✓ Secret wildcard-archpad-pro-tls already exists in namespace platform"
                exit 0
              fi
              
              echo "Secret not found in platform namespace. Searching for source secret..."
              
              # Ищем secret в разных namespace'ах (в порядке приоритета)
              SOURCE_NS=""
              for ns in argocd traefik platform; do
                if kubectl get secret wildcard-archpad-pro-tls -n "$ns" >/dev/null 2>&1; then
                  SOURCE_NS="$ns"
                  echo "Found secret in namespace: $ns"
                  break
                fi
              done
              
              if [ -z "$SOURCE_NS" ]; then
                echo "WARNING: Secret wildcard-archpad-pro-tls not found in any namespace (argocd, traefik, platform)"
                echo "The certificate may not be issued yet by cert-manager."
                echo "This is not critical - the secret will be created when cert-manager issues the certificate."
                echo "You can manually copy it later when it's available."
                exit 0  # Не считаем это ошибкой, так как cert-manager может еще не выпустить сертификат
              fi
              
              echo "Copying secret from namespace $SOURCE_NS to platform..."
              kubectl get secret wildcard-archpad-pro-tls -n "$SOURCE_NS" -o yaml | \
                sed "s/namespace: $SOURCE_NS/namespace: platform/" | \
                sed '/resourceVersion:/d' | \
                sed '/uid:/d' | \
                sed '/creationTimestamp:/d' | \
                kubectl apply -f -
              
              echo "✓ Successfully copied wildcard-archpad-pro-tls to namespace platform"
      backoffLimit: 3
