apiVersion: batch/v1
kind: Job
metadata:
  name: mailpit-copy-tls-secret
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      annotations:
        argocd.argoproj.io/hook-weight: "0"
    spec:
      serviceAccountName: default
      restartPolicy: Never
      containers:
        - name: copy-secret
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - |
              set -eu
              echo "Checking if wildcard-archpad-pro-tls exists in namespace platform..."
              
              if kubectl get secret wildcard-archpad-pro-tls -n platform >/dev/null 2>&1; then
                echo "Secret wildcard-archpad-pro-tls already exists in namespace platform"
                exit 0
              fi
              
              echo "Secret not found. Copying from namespace argocd..."
              
              if ! kubectl get secret wildcard-archpad-pro-tls -n argocd >/dev/null 2>&1; then
                echo "ERROR: Source secret wildcard-archpad-pro-tls not found in namespace argocd"
                echo "Please ensure the certificate is created first"
                exit 1
              fi
              
              kubectl get secret wildcard-archpad-pro-tls -n argocd -o yaml | \
                sed 's/namespace: argocd/namespace: platform/' | \
                sed '/resourceVersion:/d' | \
                sed '/uid:/d' | \
                sed '/creationTimestamp:/d' | \
                kubectl apply -f -
              
              echo "Successfully copied wildcard-archpad-pro-tls to namespace platform"
      backoffLimit: 3
