#!/bin/sh
set -eu


MODE="${DB_OWNERSHIP_MODE:-app_owner}"


# Create app roles
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
CREATE ROLE ${HASURA_DB_USER} LOGIN PASSWORD '${HASURA_DB_PASS}';
CREATE ROLE ${STRAPI_DB_USER} LOGIN PASSWORD '${STRAPI_DB_PASS}';
CREATE ROLE ${KEYCLOAK_DB_USER} LOGIN PASSWORD '${KEYCLOAK_DB_PASS}';
EOSQL


if [ "$MODE" = "postgres_owner" ]; then
# Databases owned by postgres; grant privileges to app users
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
CREATE DATABASE ${PROJECT_DB};
CREATE DATABASE ${HASURA_DB};
CREATE DATABASE ${STRAPI_DB};
CREATE DATABASE ${KEYCLOAK_DB};
EOSQL

# PROJECT
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$PROJECT_DB" <<-EOSQL
REVOKE ALL ON DATABASE ${PROJECT_DB} FROM PUBLIC;
GRANT CONNECT ON DATABASE ${PROJECT_DB} TO ${POSTGRES_USER};
GRANT USAGE, CREATE ON SCHEMA public TO ${POSTGRES_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO ${POSTGRES_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${POSTGRES_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO ${POSTGRES_USER};
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL


# HASURA
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$HASURA_DB" <<-EOSQL
REVOKE ALL ON DATABASE ${HASURA_DB} FROM PUBLIC;
GRANT CONNECT ON DATABASE ${HASURA_DB} TO ${HASURA_DB_USER};
GRANT USAGE, CREATE ON SCHEMA public TO ${HASURA_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO ${HASURA_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${HASURA_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO ${HASURA_DB_USER};
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL


# STRAPI
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$STRAPI_DB" <<-EOSQL
REVOKE ALL ON DATABASE ${STRAPI_DB} FROM PUBLIC;
GRANT CONNECT ON DATABASE ${STRAPI_DB} TO ${STRAPI_DB_USER};
GRANT USAGE, CREATE ON SCHEMA public TO ${STRAPI_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO ${STRAPI_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${STRAPI_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO ${STRAPI_DB_USER};
CREATE EXTENSION IF NOT EXISTS pgcrypto;
EOSQL


# KEYCLOAK
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$KEYCLOAK_DB" <<-EOSQL
REVOKE ALL ON DATABASE ${KEYCLOAK_DB} FROM PUBLIC;
GRANT CONNECT ON DATABASE ${KEYCLOAK_DB} TO ${KEYCLOAK_DB_USER};
GRANT USAGE, CREATE ON SCHEMA public TO ${KEYCLOAK_DB_USER};
EOSQL


else
# Databases owned by app users (dev-friendly default)
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
CREATE DATABASE ${PROJECT_DB} OWNER ${POSTGRES_USER};
CREATE DATABASE ${HASURA_DB} OWNER ${HASURA_DB_USER};
CREATE DATABASE ${STRAPI_DB} OWNER ${STRAPI_DB_USER};
CREATE DATABASE ${KEYCLOAK_DB} OWNER ${KEYCLOAK_DB_USER};
EOSQL


# Extensions
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$PROJECT_DB" <<-EOSQL
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$HASURA_DB" <<-EOSQL
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$STRAPI_DB" <<-EOSQL
CREATE EXTENSION IF NOT EXISTS pgcrypto;
EOSQL
fi
