apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://gitlab.com/zs-archipad/archpad.git
    targetRevision: HEAD
    path: infra/timeweb/10-gitops/apps/monitoring
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
