apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://gitlab.com/zs-archipad/archpad.git
    targetRevision: main
    path: infra/timeweb/10-gitops/apps/monitoring
    directory:
      recurse: true
      # prometheus управляется отдельным Application (`apps/monitoring/prometheus/prometheus.app.yaml`).
      # Если не исключить папку, monitoring и prometheus начинают "драться" за одни и те же ресурсы,
      # что приводит к SharedResourceWarning и бесконечной Syncing/OutOfSync.
      # Не применять свой же манифест (управляется platform-applications).
      exclude: "{prometheus/**,monitoring.app.yaml}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
  ignoreDifferences: []  # пустой массив; для игноров используйте элементы вида: - group: ... kind: ... jsonPointers: ...
