apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://gitlab.com/zs-archipad/archpad.git
    targetRevision: main
    path: infra/timeweb/10-gitops/apps/monitoring
    directory:
      recurse: true
      # prometheus управляется отдельным Application (`apps/monitoring/prometheus/prometheus.app.yaml`).
      # Если не исключить папку, monitoring и prometheus начинают "драться" за одни и те же ресурсы,
      # что приводит к SharedResourceWarning и бесконечной Syncing/OutOfSync.
      exclude: "prometheus/**"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
  ignoreDifferences:
    # (опционально) здесь можно добавлять игноры на "шумные" ресурсы,
    # но prometheus ресурсы должны быть исключены через directory.exclude выше.
