apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: landing
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  source:
    repoURL: https://gitlab.com/zs-archipad/archpad.git
    targetRevision: main
    path: infra/timeweb/10-gitops/apps/frontend/landing
    directory:
      recurse: false
      # landing.app.yaml — сам Application; turnstile secret sync — в root kustomization (wave 42)
      exclude: '{landing.app.yaml,landing-turnstile-secret-sync.job.yaml,landing-turnstile-secret-sync.serviceaccount.yaml}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
