# ServiceAccount, Role, RoleBinding for landing Turnstile secret sync
apiVersion: v1
kind: ServiceAccount
metadata:
  name: landing-turnstile-secret-sync
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: landing-turnstile-secret-sync
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "5"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: landing-turnstile-secret-sync
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: landing-turnstile-secret-sync
subjects:
  - kind: ServiceAccount
    name: landing-turnstile-secret-sync
    namespace: platform
