apiVersion: batch/v1
kind: Job
metadata:
  name: landing-turnstile-secret-sync
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    app: landing-turnstile-secret-sync
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: landing-turnstile-secret-sync
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-turnstile: "kv/data/archpad/demo/turnstile"
        vault.hashicorp.com/agent-inject-template-turnstile: |
          {{- $turnstile := secret "kv/data/archpad/demo/turnstile" }}
          export NEXT_PUBLIC_TURNSTILE_SITE_KEY="{{ $turnstile.Data.data.NEXT_PUBLIC_TURNSTILE_SITE_KEY }}"
          export TURNSTILE_SECRET_KEY="{{ $turnstile.Data.data.TURNSTILE_SECRET_KEY }}"
        vault.hashicorp.com/role: "platform"
        vault.hashicorp.com/agent-pre-populate-only: "true"
    spec:
      serviceAccountName: landing-turnstile-secret-sync
      restartPolicy: Never
      containers:
        - name: landing-turnstile-secret-sync
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - |
              set -a
              . /vault/secrets/turnstile
              set +a

              if [ -z "$NEXT_PUBLIC_TURNSTILE_SITE_KEY" ]; then
                echo "ERROR: NEXT_PUBLIC_TURNSTILE_SITE_KEY is not set"
                exit 1
              fi
              if [ -z "$TURNSTILE_SECRET_KEY" ]; then
                echo "ERROR: TURNSTILE_SECRET_KEY is not set"
                exit 1
              fi

              kubectl create secret generic landing-turnstile \
                --from-literal=NEXT_PUBLIC_TURNSTILE_SITE_KEY="$NEXT_PUBLIC_TURNSTILE_SITE_KEY" \
                --from-literal=TURNSTILE_SECRET_KEY="$TURNSTILE_SECRET_KEY" \
                --namespace=platform \
                --dry-run=client -o yaml | kubectl apply -f -

              echo "✅ Secret 'landing-turnstile' synchronized from Vault"
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
