# RBAC права для cert-manager ServiceAccount для работы с TimeWeb DNS webhook
# Создается отдельный ClusterRole и ClusterRoleBinding для работы с TimeWeb DNS webhook
# ВАЖНО: Cert-manager устанавливается как аддон в панели Timeweb, не через ArgoCD
# Но права нужно создать через ArgoCD, чтобы они были версионированы в Git

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-timeweb-webhook
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller
rules:
  - apiGroups:
      - twcloud-1067343
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-timeweb-webhook
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-timeweb-webhook
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
