export enum DirectoryKind {
  ARCHITECTURE_STYLE = 'ARCHITECTURE_STYLE',
  CRITICAL_LEVEL = 'CRITICAL_LEVEL',
  LICENSE_TYPE = 'LICENSE_TYPE',
  NODE_TYPE = 'NODE_TYPE',
  SOFTWARE_TYPE = 'SOFTWARE_TYPE',
  PROTOCOL_TYPE = 'PROTOCOL_TYPE',
}
