sources:
  docker_logs:
    type: docker_logs
    docker_host: "unix:///var/run/docker.sock"
    # Vector collects logs from all containers by default.
    # We filter by project label in the transform to ensure we only process archpad containers.
    # This allows Vector to see all containers and then filter them.

transforms:
  filter_archpad:
    type: filter
    inputs: [docker_logs]
    condition: |
      .container_labels."com.docker.compose.project" == "archpad" || 
      .container_name =~ "^archpad-"
  
  enrich:
    type: remap
    inputs: [filter_archpad]
    source: |
      .loki_labels = {}
      # In recent Vector versions, '??' is error-coalescing (not null-coalescing).
      # So we set defaults explicitly when values are null/missing.
      .loki_labels.service = .container_labels."com.docker.compose.service"
      if is_null(.loki_labels.service) { .loki_labels.service = "unknown" }
      # Grafana Logs Drilldown expects `service_name`
      .loki_labels.service_name = .loki_labels.service

      .loki_labels.project = .container_labels."com.docker.compose.project"
      if is_null(.loki_labels.project) { .loki_labels.project = "unknown" }
      # Grafana Logs Drilldown often uses `service_namespace`
      .loki_labels.service_namespace = .loki_labels.project

      .loki_labels.container = .container_name
      if is_null(.loki_labels.container) { .loki_labels.container = "unknown" }
      # Grafana Logs Drilldown often uses `service_instance_id`
      .loki_labels.service_instance_id = .loki_labels.container

      .loki_labels.image = .image
      if is_null(.loki_labels.image) { .loki_labels.image = "unknown" }

sinks:
  loki:
    type: loki
    inputs: [enrich]
    endpoint: http://loki:3100
    # Loki may return 503 while starting up; don't fail Vector startup on that.
    healthcheck:
      enabled: false
    # Retry configuration to handle temporary Loki unavailability
    request:
      retry_attempts: 5
      retry_initial_backoff_secs: 1
    encoding:
      codec: json
    labels:
      service: "{{ loki_labels.service }}"
      service_name: "{{ loki_labels.service_name }}"
      service_namespace: "{{ loki_labels.service_namespace }}"
      service_instance_id: "{{ loki_labels.service_instance_id }}"
      project: "{{ loki_labels.project }}"
      container: "{{ loki_labels.container }}"
      image: "{{ loki_labels.image }}"


