apiVersion: batch/v1
kind: Job
metadata:
  name: loki-s3-creds
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    # Re-run on every Argo sync
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    app: loki
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: loki
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-s3-bucket: "kv/data/archpad/s3/bucket"
        vault.hashicorp.com/agent-inject-secret-s3-access-key: "kv/data/archpad/s3/access-key"
        vault.hashicorp.com/agent-inject-template-loki-s3-creds: |
          {{- $b := secret "kv/data/archpad/s3/bucket" -}}
          {{- $k := secret "kv/data/archpad/s3/access-key" -}}
          export S3_BUCKET="{{ or $b.Data.data.S3_BUCKET $b.Data.data.BUCKET $b.Data.data.BUCKET_NAME }}"
          export S3_ENDPOINT="{{ or $b.Data.data.S3_ENDPOINT $b.Data.data.S3_HOST $b.Data.data.S3_URL $b.Data.data.ENDPOINT "s3.twcstorage.ru" }}"
          export S3_REGION="{{ or $b.Data.data.S3_REGION $b.Data.data.REGION "ru-1" }}"
          export S3_ACCESS_KEY_ID="{{ or $k.Data.data.AWS_ACCESS_KEY_ID $k.Data.data.S3_ACCESS_KEY_ID $k.Data.data.ACCESS_KEY_ID $k.Data.data.ACCESS_KEY }}"
          export S3_SECRET_ACCESS_KEY="{{ or $k.Data.data.AWS_SECRET_ACCESS_KEY $k.Data.data.S3_SECRET_ACCESS_KEY $k.Data.data.SECRET_ACCESS_KEY $k.Data.data.SECRET_KEY }}"
        vault.hashicorp.com/role: "platform"
        vault.hashicorp.com/agent-pre-populate-only: "true"
    spec:
      serviceAccountName: loki
      restartPolicy: Never
      containers:
        - name: loki-s3-creds
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - |
              set -a
              . /vault/secrets/loki-s3-creds
              set +a
              [ -n "$S3_BUCKET" ] || (echo "ERROR: S3_BUCKET is not set" && exit 1)
              [ -n "$S3_ACCESS_KEY_ID" ] || (echo "ERROR: S3_ACCESS_KEY_ID is not set" && exit 1)
              [ -n "$S3_SECRET_ACCESS_KEY" ] || (echo "ERROR: S3_SECRET_ACCESS_KEY is not set" && exit 1)
              [ -n "$S3_ENDPOINT" ] || (echo "ERROR: S3_ENDPOINT is not set" && exit 1)
              [ -n "$S3_REGION" ] || (echo "ERROR: S3_REGION is not set" && exit 1)

              kubectl -n monitoring create secret generic loki-s3-creds \
                --from-literal=S3_BUCKET="$S3_BUCKET" \
                --from-literal=S3_ENDPOINT="$S3_ENDPOINT" \
                --from-literal=S3_REGION="$S3_REGION" \
                --from-literal=S3_ACCESS_KEY_ID="$S3_ACCESS_KEY_ID" \
                --from-literal=S3_SECRET_ACCESS_KEY="$S3_SECRET_ACCESS_KEY" \
                --dry-run=client -o yaml | kubectl apply -f -

              echo "✅ Secret monitoring/loki-s3-creds synced from Vault"
