apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-s3
  namespace: monitoring
  labels:
    app: loki
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-s3
  resources:
    requests:
      storage: 10Gi
