apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki-s3-creds-writer
  namespace: monitoring
  labels:
    app: loki
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loki-s3-creds-writer
  namespace: monitoring
  labels:
    app: loki
subjects:
  - kind: ServiceAccount
    name: loki
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loki-s3-creds-writer
