auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  # Newer Loki versions don't use `shared_store` here; retention is handled by the compactor itself.
  retention_enabled: true
  delete_request_store: filesystem

limits_config:
  retention_period: 168h
  # Loki 3.x validates "structured metadata" requirements (schema v13 + tsdb).
  # We don't need native OTLP ingestion for logs here, so disable it for local dev.
  allow_structured_metadata: false


