apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj-labs/argocd-image-updater
    targetRevision: HEAD
    path: manifests/base
    helm:
      valueFiles:
        - values.yaml
      values: |
        # Настройки для работы с TimeWeb Container Registry
        config:
          registries:
            - name: TimeWeb Container Registry
              prefix: archpad-cr.registry.twcstorage.ru
              api_url: https://archpad-cr.registry.twcstorage.ru
              credentials: ext:/scripts/archpad-registry-secret
              default: true
          git:
            user: argocd-image-updater
            email: argocd-image-updater@archpad.pro
            ssh_secret: argocd-image-updater-git-ssh-key
          log:
            level: info
          check:
            interval: 2m
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
