apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: secure
  source:
    repoURL: https://gitlab.com/zs-archipad/archpad.git
    targetRevision: main
    path: infra/timeweb/10-gitops/apps/keycloak
    directory:
      recurse: false
      exclude: keycloak.app.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    # Vault Agent Injector mutates pod spec (init containers + sidecar).
    - group: apps
      kind: Deployment
      name: keycloak
      namespace: secure
      jsonPointers:
        - /spec/template/spec
