apiVersion: batch/v1
kind: CronJob
metadata:
  name: keycloak-sync
  namespace: secure
  annotations:
    argocd.argoproj.io/sync-wave: "90"
spec:
  # Sync "desired state" (roles/groups/clients) periodically.
  # ArgoCD applies manifests, and this job applies them inside Keycloak via Admin API.
  schedule: "*/10 * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            # Do not keep a long-running vault-agent sidecar in a Job/CronJob.
            # We only need init-time templating of secrets into files.
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-secret-keycloak-admin: "kv/data/archpad/demo/keycloak/admin"
            vault.hashicorp.com/agent-inject-template-keycloak-admin: |
              {{- with secret "kv/data/archpad/demo/keycloak/admin" }}
              export KEYCLOAK_ADMIN="{{ .Data.data.KEYCLOAK_ADMIN_USER }}"
              export KEYCLOAK_ADMIN_PASSWORD="{{ .Data.data.KEYCLOAK_ADMIN_PASSWORD }}"
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-oidc-portal: "kv/data/archpad/demo/oidc/portal"
            vault.hashicorp.com/agent-inject-template-oidc-portal: |
              {{- with secret "kv/data/archpad/demo/oidc/portal" }}
              {{- if .Data.data.OIDC_CLIENT_ID }}
              export OIDC_CLIENT_ID="{{ .Data.data.OIDC_CLIENT_ID }}"
              {{- end }}
              {{- if .Data.data.OIDC_CLIENT_SECRET }}
              export OIDC_CLIENT_SECRET="{{ .Data.data.OIDC_CLIENT_SECRET }}"
              {{- end }}
              {{- end }}
            vault.hashicorp.com/role: "secure"
        spec:
          serviceAccountName: keycloak
          restartPolicy: Never
          containers:
            - name: keycloak-sync
              image: alpine:3.19
              command: ["sh", "-ceu"]
              args:
                - |
                  apk add --no-cache curl jq >/dev/null
                  # Load admin creds from Vault Agent Injector
                  . /vault/secrets/keycloak-admin
                  # Load portal OIDC client id/secret (confidential client)
                  . /vault/secrets/oidc-portal || true

                  KC_BASE="http://keycloak:8080"
                  REALM="archpad"
                  PORTAL_CLIENT_ID="${OIDC_CLIENT_ID:-archpad-portal}"

                  # Wait until realm exists (first boot can take a bit).
                  for i in $(seq 1 60); do
                    if curl -fsS "${KC_BASE}/realms/${REALM}" >/dev/null; then
                      break
                    fi
                    sleep 2
                  done

                  # Get admin token from master realm using admin-cli.
                  token_json="$(curl -fsS -X POST "${KC_BASE}/realms/master/protocol/openid-connect/token" \
                    -H "Content-Type: application/x-www-form-urlencoded" \
                    --data-urlencode "grant_type=password" \
                    --data-urlencode "client_id=admin-cli" \
                    --data-urlencode "username=${KEYCLOAK_ADMIN}" \
                    --data-urlencode "password=${KEYCLOAK_ADMIN_PASSWORD}")"
                  access_token="$(printf "%s" "$token_json" | jq -r '.access_token')"
                  [ -n "$access_token" ]

                  # Apply partial import (roles/groups/clients) from ConfigMap.
                  # NOTE: partialImport for groups can be buggy in some Keycloak versions; we sync groups via Admin API below.
                  code="$(curl -sS -o /tmp/resp.json -w "%{http_code}" \
                    -X POST "${KC_BASE}/admin/realms/${REALM}/partialImport" \
                    -H "Authorization: Bearer ${access_token}" \
                    -H "Content-Type: application/json" \
                    --data-binary "@/config/partial-import.json" || true)"

                  echo "partialImport status=${code}"
                  # 200 is expected on success.
                  if [ "$code" != "200" ]; then
                    echo "Response:"
                    cat /tmp/resp.json || true
                    exit 1
                  fi
                  cat /tmp/resp.json

                  # Sync groups (create if missing).
                  if [ -f /config/groups.json ]; then
                    jq -r '.[] | .name' /config/groups.json | while read -r name; do
                      [ -n "$name" ] || continue
                      # Search group by name (returns array).
                      existing="$(curl -fsS \
                        -H "Authorization: Bearer ${access_token}" \
                        "${KC_BASE}/admin/realms/${REALM}/groups?search=$(printf %s "$name" | jq -sRr @uri)" \
                        | jq -r --arg n "$name" '[.[] | select(.name == $n)][0].id // empty')"
                      if [ -n "$existing" ]; then
                        echo "group exists: $name"
                        continue
                      fi
                      echo "creating group: $name"
                      curl -fsS -X POST "${KC_BASE}/admin/realms/${REALM}/groups" \
                        -H "Authorization: Bearer ${access_token}" \
                        -H "Content-Type: application/json" \
                        -d "$(jq -cn --arg n "$name" '{name:$n}')" >/dev/null
                    done
                  fi

                  # Ensure portal client is confidential and has the configured secret.
                  if [ -n "${OIDC_CLIENT_SECRET:-}" ]; then
                    portal_id="$(curl -fsS \
                      -H "Authorization: Bearer ${access_token}" \
                      "${KC_BASE}/admin/realms/${REALM}/clients?clientId=${PORTAL_CLIENT_ID}" \
                      | jq -r '.[0].id // empty')"
                    if [ -z "$portal_id" ]; then
                      echo "ERROR: portal client not found: ${PORTAL_CLIENT_ID}"
                      exit 1
                    fi

                    # Fetch client representation and update secret + flags.
                    current="$(curl -fsS -H "Authorization: Bearer ${access_token}" \
                      "${KC_BASE}/admin/realms/${REALM}/clients/${portal_id}")"
                    updated="$(printf "%s" "$current" | jq --arg s "${OIDC_CLIENT_SECRET}" '
                      .publicClient = false
                      | .serviceAccountsEnabled = false
                      | .directAccessGrantsEnabled = true
                      | .standardFlowEnabled = true
                      | .secret = $s
                    ')"

                    curl -fsS -X PUT \
                      -H "Authorization: Bearer ${access_token}" \
                      -H "Content-Type: application/json" \
                      --data-binary "$(printf "%s" "$updated")" \
                      "${KC_BASE}/admin/realms/${REALM}/clients/${portal_id}" >/dev/null
                    echo "portal client secret synced: ${PORTAL_CLIENT_ID}"
                  else
                    echo "WARNING: OIDC_CLIENT_SECRET is not set; portal client secret not synced"
                  fi
              volumeMounts:
                - name: partial-import
                  mountPath: /config/partial-import.json
                  subPath: partial-import.json
                  readOnly: true
                - name: partial-import
                  mountPath: /config/groups.json
                  subPath: groups.json
                  readOnly: true
          volumes:
            - name: partial-import
              configMap:
                name: keycloak-partial-import
