apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-export
  namespace: secure
  annotations:
    argocd.argoproj.io/sync-wave: "48"
data:
  realm-export.json: |
    {
      "realm": "archpad",
      "enabled": true,
      "displayName": "Archpad",
      "registrationAllowed": false,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": true,
      "rememberMe": true,
      "clients": [
        {
          "clientId": "archpad-portal",
          "name": "archpad-portal",
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": false,
          "redirectUris": [
            "https://portal.archpad.pro/*",
            "http://localhost:3000/*"
          ],
          "webOrigins": [
            "https://portal.archpad.pro",
            "http://localhost:3000"
          ]
        },
        {
          "clientId": "portal-admin",
          "name": "portal-admin",
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": false,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": true
        },
        {
          "clientId": "api",
          "name": "api",
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": false,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": true
        }
      ],
      "users": [
        {
          "username": "service-account-portal-admin",
          "enabled": true,
          "serviceAccountClientId": "portal-admin",
          "clientRoles": {
            "realm-management": [
              "view-users",
              "manage-users"
            ]
          }
        }
      ]
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-import
  namespace: secure
  annotations:
    # Admin operation: execute manually from ArgoCD UI when needed.
    argocd.argoproj.io/hook: Manual
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "49"
spec:
  backoffLimit: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-keycloak-admin: "kv/data/archpad/demo/keycloak/admin"
        vault.hashicorp.com/agent-inject-secret-keycloak-db: "kv/data/archpad/demo/keycloak/db"
        vault.hashicorp.com/agent-inject-secret-keycloak-connect: "kv/data/archpad/demo/keycloak/connect"
        vault.hashicorp.com/agent-inject-secret-postgres-connect: "kv/data/archpad/demo/postgres/connect"
        vault.hashicorp.com/agent-inject-secret-keycloak-smtp: "kv/data/archpad/demo/keycloak/smtp"
        vault.hashicorp.com/agent-inject-template-keycloak: |
          {{- $admin := secret "kv/data/archpad/demo/keycloak/admin" }}
          {{- $db := secret "kv/data/archpad/demo/keycloak/db" }}
          {{- $connect := secret "kv/data/archpad/demo/keycloak/connect" }}
          {{- $postgres := secret "kv/data/archpad/demo/postgres/connect" }}
          {{- $smtp := secret "kv/data/archpad/demo/keycloak/smtp" }}
          # Admin bootstrap (not required for import, but keeps env consistent with deployment)
          export KEYCLOAK_ADMIN="{{ $admin.Data.data.KEYCLOAK_ADMIN_USER }}"
          export KEYCLOAK_ADMIN_PASSWORD="{{ $admin.Data.data.KEYCLOAK_ADMIN_PASSWORD }}"

          # Hostnames
          export KC_HOSTNAME="https://{{ $connect.Data.data.KEYCLOAK_HOST }}"

          # Database
          export KC_DB="postgres"
          export KC_DB_USERNAME="{{ $db.Data.data.KEYCLOAK_DB_USER }}"
          export KC_DB_PASSWORD="{{ $db.Data.data.KEYCLOAK_DB_PASSWORD }}"
          export KC_DB_URL="jdbc:postgresql://{{ $postgres.Data.data.POSTGRES_ENDPOINT }}:{{ $postgres.Data.data.POSTGRES_PORT }}/{{ $db.Data.data.KEYCLOAK_DB }}"

          # SMTP (optional)
          {{- if $smtp.Data.data.SMTP_INTERNAL_URL }}
          export KC_MAIL_HOST="{{ $smtp.Data.data.SMTP_INTERNAL_URL }}"
          {{- end }}
          {{- if $smtp.Data.data.SMTP_PORT }}
          export KC_MAIL_PORT="{{ $smtp.Data.data.SMTP_PORT }}"
          {{- end }}
          {{- if $smtp.Data.data.SMTP_USER }}
          export KC_MAIL_USER="{{ $smtp.Data.data.SMTP_USER }}"
          {{- end }}
          {{- if $smtp.Data.data.SMTP_PASSWORD }}
          export KC_MAIL_PASSWORD="{{ $smtp.Data.data.SMTP_PASSWORD }}"
          {{- end }}
          {{- if $smtp.Data.data.SMTP_FROM_ADDRESS }}
          export KC_MAIL_FROM="{{ $smtp.Data.data.SMTP_FROM_ADDRESS }}"
          {{- end }}
        vault.hashicorp.com/role: "secure"
    spec:
      serviceAccountName: keycloak
      restartPolicy: Never
      containers:
        - name: keycloak-import
          image: quay.io/keycloak/keycloak:latest
          command: ["sh", "-c"]
          args:
            - |
              set -euo pipefail
              # Load env rendered by Vault Agent Injector.
              if [ -f /vault/secrets/keycloak ]; then
                set -a
                . /vault/secrets/keycloak
                set +a
              else
                echo "ERROR: /vault/secrets/keycloak not found"
                exit 1
              fi

              exec /opt/keycloak/bin/kc.sh import --file=/import/realm-export.json --override=true
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 768Mi
          volumeMounts:
            - name: realm-export
              mountPath: /import/realm-export.json
              subPath: realm-export.json
              readOnly: true
      volumes:
        - name: realm-export
          configMap:
            name: keycloak-realm-export
