apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  source:
    # Используем Git репозиторий напрямую, так как Helm репозиторий HashiCorp недоступен (403)
    # ArgoCD может работать с Helm чартами из Git репозиториев
    repoURL: https://github.com/hashicorp/vault-helm.git
    targetRevision: v0.31.0
    path: .
    helm:
      releaseName: vault
      values: |
        global:
          enabled: true

        server:
          # Используем последнюю стабильную версию Vault
          image:
            repository: hashicorp/vault
            tag: "1.18.0"

          # HA режим отключен при использовании S3 storage
          # S3 storage позволяет использовать одну реплику без проблем
          ha:
            enabled: false
            replicas: 1

          # Raft storage отключен, используем S3 storage
          raft:
            enabled: false

          # UI включен для доступа через веб-интерфейс
          ui:
            enabled: true

          # Сервис ClusterIP на стандартном порту Vault
          service:
            enabled: true
            type: ClusterIP
            port: 8200

          # PersistentVolume не нужен при использовании S3 storage
          # Отключаем file storage, чтобы Vault не использовал локальное хранилище
          dataStorage:
            enabled: false

          # Отключаем file storage backend по умолчанию
          # Это важно, чтобы Vault использовал только S3 из extraConfig
          # Helm chart по умолчанию может использовать file storage, если не отключить явно
          extraVolumes: []

          # Настройка securityContext для автоматической настройки прав доступа
          # fsGroup автоматически настроит права для volumes
          securityContext:
            fsGroup: 1000
            runAsUser: 100
            runAsGroup: 1000
            runAsNonRoot: true

          # Конфигурация S3 backend для Vault
          # ВАЖНО: extraConfig добавляется в конец конфигурации Vault
          # Если Helm chart создает дефолтный storage "file", он будет использован первым
          # Поэтому нужно явно отключить file storage через dataStorage.enabled: false
          # и убедиться, что S3 storage определен в extraConfig
          extraConfig: |
            # Отключаем file storage, если он был определен по умолчанию
            # Vault использует первый найденный storage backend в конфигурации
            # Поэтому важно, чтобы S3 был единственным storage backend
            storage "s3" {
              access_key = "1V87S1B2IPAWIR1K0SL8"
              secret_key = "LMWtBOQE4xAq4klbAaosjPuRHqRjKxBEZUkUZYhj"
              bucket     = "9f328daa-archpad-s3-storage"
              endpoint   = "https://s3.twcstorage.ru"
              region     = "ru-1"
              path       = "vault-secret/"
            }
            
            disable_mlock = true

          # Отключаем webhooks для упрощения развертывания
          disableWebhooks: true

        # Настройка Vault Agent Injector для уменьшения CPU requests
        # Фактическое использование очень низкое (~5-10m), но дефолтные requests 250m
        # Уменьшаем до 50m, чтобы освободить ресурсы для других подов
        injector:
          enabled: true
          # Уменьшаем CPU requests для Vault Agent init контейнеров
          # Это освободит ~200m CPU на каждый под с Vault Agent
          resources:
            requests:
              cpu: 50m  # Было 250m по умолчанию
              memory: 64Mi
            limits:
              cpu: 100m  # Было 500m по умолчанию
              memory: 128Mi
          # Переопределяем переменные окружения для уменьшения requests
          # Эти переменные контролируют ресурсы для init контейнеров vault-agent-init
          extraEnvironmentVars:
            AGENT_INJECT_CPU_REQUEST: "50m"
            AGENT_INJECT_CPU_LIMIT: "100m"
            AGENT_INJECT_MEM_REQUEST: "64Mi"
            AGENT_INJECT_MEM_LIMIT: "128Mi"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
