{
 "title": "Keycloak",
 "tags": [
  "archpad",
  "keycloak"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Keycloak Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"kubernetes-services\", kubernetes_namespace=\"secure\", kubernetes_name=\"keycloak\"}"
    }
   ]
  },
  {
   "title": "Scrape duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"kubernetes-services\", kubernetes_namespace=\"secure\", kubernetes_name=\"keycloak\"}"
    }
   ]
  },
  {
   "title": "Process RSS (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kubernetes-services\", kubernetes_namespace=\"secure\", kubernetes_name=\"keycloak\"}"
    }
   ]
  },
  {
   "title": "JVM heap used (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"kubernetes-services\", kubernetes_namespace=\"secure\", kubernetes_name=\"keycloak\", area=\"heap\"}"
    }
   ]
  }
 ]
}