export enum MotivationKind {
  ASSESSMENT = 'ASSESSMENT',
  CONSTRAINT = 'CONSTRAINT',
  PRINCIPLE = 'PRINCIPLE',
  REQUIREMENT = 'REQUIREMENT',
  RISK = 'RISK',
  CAPABILITY_ASSESSMENT = 'CAPABILITY_ASSESSMENT',
}
