export enum StakeholderRole {
  EXECUTIVE_SPONSOR = 'stakeholder.role.executive-sponsor',
  BUSINESS_OWNER = 'stakeholder.role.business-owner',
  PRODUCT_OWNER = 'stakeholder.role.product-owner',
  PRODUCT_MANAGER = 'stakeholder.role.product-manager',
  SERVICE_OWNER = 'stakeholder.role.service-owner',
  PROCESS_OWNER = 'stakeholder.role.process-owner',
  DOMAIN_OWNER = 'stakeholder.role.domain-owner',
  CUSTOMER_REPRESENTATIVE = 'stakeholder.role.customer-representative',
  END_USER_REPRESENTATIVE = 'stakeholder.role.end-user-representative',
  
  ENTERPRISE_ARCHITECT = 'stakeholder.role.enterprise-architect',
  SOLUTION_ARCHITECT = 'stakeholder.role.solution-architect',
  DOMAIN_ARCHITECT = 'stakeholder.role.domain-architect',
  APPLICATION_ARCHITECT = 'stakeholder.role.application-architect',
  INTEGRATION_ARCHITECT = 'stakeholder.role.integration-architect',
  DATA_ARCHITECT = 'stakeholder.role.data-architect',
  SECURITY_ARCHITECT = 'stakeholder.role.security-architect',
  PLATFORM_ARCHITECT = 'stakeholder.role.platform-architect',
  CLOUD_ARCHITECT = 'stakeholder.role.cloud-architect',
  NETWORK_ARCHITECT = 'stakeholder.role.network-architect',
  INFRASTRUCTURE_ARCHITECT = 'stakeholder.role.infrastructure-architect',
  
  ENGINEERING_MANAGER = 'stakeholder.role.engineering-manager',
  TECH_LEAD = 'stakeholder.role.tech-lead',
  DEVELOPMENT_LEAD = 'stakeholder.role.development-lead',
  SOFTWARE_ENGINEER = 'stakeholder.role.software-engineer',
  INTEGRATION_ENGINEER = 'stakeholder.role.integration-engineer',
  DATA_ENGINEER = 'stakeholder.role.data-engineer',
  QA_LEAD = 'stakeholder.role.qa-lead',
  QA_ENGINEER = 'stakeholder.role.qa-engineer',
  RELEASE_MANAGER = 'stakeholder.role.release-manager',
  BUILD_ENGINEER = 'stakeholder.role.build-engineer',
  CONFIGURATION_MANAGER = 'stakeholder.role.configuration-manager',
  
  SRE = 'stakeholder.role.sre',
  DEVOPS_ENGINEER = 'stakeholder.role.devops-engineer',
  OPERATIONS_ENGINEER = 'stakeholder.role.operations-engineer',
  SERVICE_MANAGER = 'stakeholder.role.service-manager',
  SUPPORT_ENGINEER = 'stakeholder.role.support-engineer',
  INCIDENT_MANAGER = 'stakeholder.role.incident-manager',
  PROBLEM_MANAGER = 'stakeholder.role.problem-manager',
  CHANGE_MANAGER = 'stakeholder.role.change-manager',
  AVAILABILITY_MANAGER = 'stakeholder.role.availability-manager',
  CAPACITY_MANAGER = 'stakeholder.role.capacity-manager',
  CONTINUITY_MANAGER = 'stakeholder.role.continuity-manager',
  OBSERVABILITY_OWNER = 'stakeholder.role.observability-owner',
  
  CISO = 'stakeholder.role.ciso',
  SECURITY_OFFICER = 'stakeholder.role.security-officer',
  RISK_MANAGER = 'stakeholder.role.risk-manager',
  COMPLIANCE_OFFICER = 'stakeholder.role.compliance-officer',
  PRIVACY_OFFICER = 'stakeholder.role.privacy-officer',
  INTERNAL_AUDITOR = 'stakeholder.role.internal-auditor',
  EXTERNAL_AUDITOR = 'stakeholder.role.external-auditor',
  SOC_ANALYST = 'stakeholder.role.soc-analyst',
  IAM_ADMINISTRATOR = 'stakeholder.role.iam-administrator',
  SECURITY_ENGINEER = 'stakeholder.role.security-engineer',
  
  DATA_OWNER = 'stakeholder.role.data-owner',
  DATA_STEWARD = 'stakeholder.role.data-steward',
  ANALYTICS_OWNER = 'stakeholder.role.analytics-owner',
  ML_OWNER = 'stakeholder.role.ml-owner',
  
  PROJECT_MANAGER = 'stakeholder.role.project-manager',
  PROGRAM_MANAGER = 'stakeholder.role.program-manager',
  PORTFOLIO_MANAGER = 'stakeholder.role.portfolio-manager',
  SCRUM_MASTER = 'stakeholder.role.scrum-master',
  AGILE_COACH = 'stakeholder.role.agile-coach',
  RELEASE_TRAIN_ENGINEER = 'stakeholder.role.release-train-engineer',
  
  FINOPS_OWNER = 'stakeholder.role.finops-owner',
  PROCUREMENT_SPECIALIST = 'stakeholder.role.procurement-specialist',
  VENDOR_MANAGER = 'stakeholder.role.vendor-manager',
  LEGAL_COUNSEL = 'stakeholder.role.legal-counsel',
  EXTERNAL_VENDOR = 'stakeholder.role.external-vendor',
  REGULATOR = 'stakeholder.role.regulator',
  
  UX_DESIGNER = 'stakeholder.role.ux-designer',
  UX_RESEARCHER = 'stakeholder.role.ux-researcher',
  TECHNICAL_WRITER = 'stakeholder.role.technical-writer',
}
