apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hasura-sync-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  source:
    repoURL: https://gitlab.com/zs-archipad/archpad.git
    targetRevision: HEAD
    path: infra/timeweb/10-gitops/apps/backend/hasura-sync-service
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
