apiVersion: v1
kind: ServiceAccount
metadata:
  name: hasura-sync-service
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "45"
imagePullSecrets:
  - name: archpad-registry-secret