apiVersion: batch/v1
kind: Job
metadata:
  name: hasura-sync-service
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "60"
    # ArgoCD будет пересоздавать Job при каждом синхронизации
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    # ArgoCD Image Updater: отслеживание обновлений образа
    argocd-image-updater.argoproj.io/image-list: hasura-sync-service=archpad-cr.registry.twcstorage.ru/archpad/hasura-sync-service
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
  labels:
    app: hasura-sync-service
spec:
  # Job должен выполняться только один раз
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: hasura-sync-service
      annotations:
        # Vault Agent Injector аннотации для чтения секретов из Vault
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-hasura-sync-service: "kv/data/archpad/demo/backend/hasura-sync-service"
        vault.hashicorp.com/agent-inject-secret-hasura-secret: "kv/data/archpad/demo/hasura/secret"
        vault.hashicorp.com/agent-inject-secret-hasura-endpoint: "kv/data/archpad/demo/hasura/endpoint"
        vault.hashicorp.com/agent-inject-secret-common: "kv/data/archpad/demo/backend/common"
        vault.hashicorp.com/agent-inject-secret-postgres-connect: "kv/data/archpad/demo/postgres/connect"
        vault.hashicorp.com/agent-inject-secret-postgres-credential: "kv/data/archpad/demo/postgres/credential"
        vault.hashicorp.com/agent-inject-template-hasura-sync-service: |
          {{- $hasuraSync := secret "kv/data/archpad/demo/backend/hasura-sync-service" }}
          {{- $hasuraSecret := secret "kv/data/archpad/demo/hasura/secret" }}
          {{- $hasuraEndpoint := secret "kv/data/archpad/demo/hasura/endpoint" }}
          {{- $common := secret "kv/data/archpad/demo/backend/common" }}
          {{- $postgresConnect := secret "kv/data/archpad/demo/postgres/connect" }}
          {{- $postgresCredential := secret "kv/data/archpad/demo/postgres/credential" }}
          # Экспортируем переменные окружения для hasura-sync-service
          export HASURA_INTERNAL_URL="{{ $hasuraEndpoint.Data.data.HASURA_INTERNAL_URL }}"
          export HASURA_ENDPOINT="{{ $hasuraEndpoint.Data.data.HASURA_INTERNAL_URL }}"
          export HASURA_GRAPHQL_ADMIN_SECRET="{{ $hasuraSecret.Data.data.HASURA_GRAPHQL_ADMIN_SECRET }}"
          {{- if $hasuraSync.Data.data.HASURA_SOURCES }}
          export HASURA_SOURCES="{{ $hasuraSync.Data.data.HASURA_SOURCES }}"
          {{- else }}
          export HASURA_SOURCES="{{ $hasuraSync.Data.data.HASURA_SOURCE }}"
          {{- end }}
          export HASURA_SCHEMA="{{ $hasuraSync.Data.data.HASURA_SCHEMA }}"
          {{- if $hasuraSync.Data.data.HASURA_RENAME_COLUMNS_CAMELCASE }}
          export HASURA_RENAME_COLUMNS_CAMELCASE="{{ $hasuraSync.Data.data.HASURA_RENAME_COLUMNS_CAMELCASE }}"
          {{- end }}
          {{- if $hasuraSync.Data.data.HASURA_APPLY_DEFAULT_PERMISSIONS }}
          export HASURA_APPLY_DEFAULT_PERMISSIONS="{{ $hasuraSync.Data.data.HASURA_APPLY_DEFAULT_PERMISSIONS }}"
          {{- end }}
          {{- if $hasuraSync.Data.data.HASURA_DEFAULT_ROLE }}
          export HASURA_DEFAULT_ROLE="{{ $hasuraSync.Data.data.HASURA_DEFAULT_ROLE }}"
          {{- end }}
          export PROJECT_DB_USER="{{ $common.Data.data.PROJECT_DB_USER }}"
          export PROJECT_DB_PASSWORD="{{ $common.Data.data.PROJECT_DB_PASSWORD }}"
          export POSTGRES_HOST="{{ $postgresConnect.Data.data.POSTGRES_HOST }}"
          export POSTGRES_PORT="{{ $postgresConnect.Data.data.POSTGRES_PORT }}"
        vault.hashicorp.com/role: "platform"
        # Vault Agent должен завершиться после загрузки секретов
        vault.hashicorp.com/agent-pre-populate-only: "true"
    spec:
      serviceAccountName: hasura-sync-service
      restartPolicy: Never
      containers:
        - name: hasura-sync-service
          image: archpad-cr.registry.twcstorage.ru/archpad/hasura-sync-service:latest
          command: ["sh", "-c"]
          args:
            - |
              # Загружаем секреты из Vault Agent Injector
              set -a
              . /vault/secrets/hasura-sync-service
              set +a
              # Проверяем, что переменные установлены
              if [ -z "$HASURA_INTERNAL_URL" ]; then
                echo "ERROR: HASURA_INTERNAL_URL is not set"
                exit 1
              fi
              if [ -z "$HASURA_GRAPHQL_ADMIN_SECRET" ]; then
                echo "ERROR: HASURA_GRAPHQL_ADMIN_SECRET is not set"
                exit 1
              fi
              if [ -z "${HASURA_SOURCES:-}" ]; then
                echo "ERROR: HASURA_SOURCES is not set"
                exit 1
              fi
              if [ -z "$HASURA_SCHEMA" ]; then
                echo "ERROR: HASURA_SCHEMA is not set"
                exit 1
              fi
              echo "Hasura endpoint: $HASURA_ENDPOINT"
              echo "Hasura sources: $HASURA_SOURCES"
              echo "Hasura schema: $HASURA_SCHEMA"

              # Wait for dependent services to be ready.
              echo "Waiting for arch-repo-service (/healthz)..."
              tries=90
              until curl -fsS --max-time 2 "http://arch-repo-service:3000/healthz" >/dev/null 2>&1; do
                tries=$((tries-1))
                if [ "$tries" -le 0 ]; then
                  echo "ERROR: arch-repo-service is not ready (http://arch-repo-service:3000/healthz)"
                  exit 1
                fi
                sleep 2
              done
              echo "arch-repo-service ready"

              echo "Waiting for tenant-service (/healthz)..."
              tries=90
              until curl -fsS --max-time 2 "http://tenant-service:3000/healthz" >/dev/null 2>&1; do
                tries=$((tries-1))
                if [ "$tries" -le 0 ]; then
                  echo "ERROR: tenant-service is not ready (http://tenant-service:3000/healthz)"
                  exit 1
                fi
                sleep 2
              done
              echo "tenant-service ready"

              # Run sync (supports HASURA_SOURCES space-separated).
              exec node dist/apps/hasura-sync-service/apps/hasura-sync-service/src/main.js
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            # Оптимизировано для демо-стенда (2 ноды по 2 CPU, 2GB RAM)
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
