apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hasura-sync-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    # ArgoCD Image Updater: настройка отслеживания образов
    argocd-image-updater.argoproj.io/image-list: hasura-sync-service=archpad-cr.registry.twcstorage.ru/archpad/hasura-sync-service
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    # Стратегия обновления: использовать latest тег
    argocd-image-updater.argoproj.io/hasura-sync-service.update-strategy: latest
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  source:
    repoURL: https://gitlab.com/zs-archipad/archpad.git
    targetRevision: HEAD
    path: infra/timeweb/10-gitops/apps/backend/hasura-sync-service
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
