apiVersion: batch/v1
kind: Job
metadata:
  name: hydra-migrate
  namespace: secure
  annotations:
    argocd.argoproj.io/sync-wave: "55"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      annotations:
        # Vault Agent Injector аннотации для чтения секретов из Vault
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-hydra: "kv/data/archpad/demo/ory/hydra"
        vault.hashicorp.com/agent-inject-secret-postgres: "kv/data/archpad/demo/postgres"
        vault.hashicorp.com/agent-inject-template-hydra: |
          {{- $hydra := secret "kv/data/archpad/demo/ory/hydra" }}
          {{- $postgres := secret "kv/data/archpad/demo/postgres" }}
          # Формируем DSN из компонентов
          {{- $password := $hydra.Data.data.HYDRA_DB_PASSWORD | urlquery }}
          {{- $pgHost := $postgres.Data.data.POSTGRES_HOST }}
          {{- $pgPort := $postgres.Data.data.POSTGRES_PORT }}
          export DSN="postgres://{{ $hydra.Data.data.HYDRA_DB_USER }}:{{ $password }}@{{ $pgHost }}:{{ $pgPort }}/{{ $hydra.Data.data.HYDRA_DB }}?sslmode=disable&max_conns=20&max_idle_conns=4"
          export SECRETS_SYSTEM="{{ $hydra.Data.data.SECRETS_SYSTEM }}"
        vault.hashicorp.com/role: "secure"
    spec:
      serviceAccountName: hydra
      restartPolicy: Never
      containers:
        - name: hydra-migrate
          image: oryd/hydra:v25.4.0
          command: ["sh", "-c"]
          args:
            - |
              source /vault/secrets/hydra
              exec hydra migrate sql -e --yes -c /etc/config/hydra.yml
          volumeMounts:
            - name: config
              mountPath: /etc/config/hydra.yml
              subPath: hydra.yml
      volumes:
        - name: config
          configMap:
            name: hydra
  backoffLimit: 3
