apiVersion: batch/v1
kind: Job
metadata:
  name: registry-secret-sync
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    # ArgoCD будет пересоздавать Job при каждой синхронизации
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    app: registry-secret-sync
spec:
  # Job должен выполняться только один раз
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: registry-secret-sync
      annotations:
        # Vault Agent Injector аннотации для чтения секретов из Vault
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-registry: "kv/data/container-register"
        vault.hashicorp.com/agent-inject-template-registry: |
          {{- $registry := secret "kv/data/container-register" }}
          # Экспортируем переменные окружения для Container Registry
          export REGISTRY_URL="{{ $registry.Data.data.REGISTRY_URL }}"
          export REGISTRY_USERNAME="{{ $registry.Data.data.REGISTRY_USERNAME }}"
          export REGISTRY_PASSWORD="{{ $registry.Data.data.REGISTRY_PASSWORD }}"
        vault.hashicorp.com/role: "platform"
        # Vault Agent должен завершиться после загрузки секретов
        vault.hashicorp.com/agent-pre-populate-only: "true"
    spec:
      serviceAccountName: registry-secret-sync
      restartPolicy: Never
      containers:
        - name: registry-secret-sync
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - |
              # Загружаем секреты из Vault Agent Injector
              set -a
              . /vault/secrets/registry
              set +a
              
              # Проверяем, что переменные установлены
              if [ -z "$REGISTRY_URL" ]; then
                echo "ERROR: REGISTRY_URL is not set"
                exit 1
              fi
              if [ -z "$REGISTRY_USERNAME" ]; then
                echo "ERROR: REGISTRY_USERNAME is not set"
                exit 1
              fi
              if [ -z "$REGISTRY_PASSWORD" ]; then
                echo "ERROR: REGISTRY_PASSWORD is not set"
                exit 1
              fi
              
              echo "Creating registry secret from Vault..."
              echo "  Registry URL: $REGISTRY_URL"
              echo "  Username: $REGISTRY_USERNAME"
              
              # Создаем .dockerconfigjson
              DOCKERCONFIGJSON=$(echo -n "{\"auths\":{\"${REGISTRY_URL}\":{\"username\":\"${REGISTRY_USERNAME}\",\"password\":\"${REGISTRY_PASSWORD}\",\"auth\":\"$(echo -n "${REGISTRY_USERNAME}:${REGISTRY_PASSWORD}" | base64)\"}}}" | base64 -w 0)
              
              # Создаем или обновляем Secret
              kubectl create secret docker-registry archpad-registry-secret \
                --docker-server="${REGISTRY_URL}" \
                --docker-username="${REGISTRY_USERNAME}" \
                --docker-password="${REGISTRY_PASSWORD}" \
                --namespace=platform \
                --dry-run=client -o yaml | kubectl apply -f -
              
              echo "✅ Secret 'archpad-registry-secret' synchronized from Vault"
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            # Оптимизировано для демо-стенда (2 ноды по 2 CPU, 2GB RAM)
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
