apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-secret-sync
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  source:
    repoURL: https://gitlab.com/zs-archipad/archpad.git
    targetRevision: HEAD
    path: infra/timeweb/10-gitops/apps/backend
    directory:
      recurse: false
      include: |
        registry-secret-sync.*
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
