apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-secret-sync
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    # Ensure this exists BEFORE the PreSync Job runs
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-secret-sync
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-secret-sync
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: registry-secret-sync
subjects:
  - kind: ServiceAccount
    name: registry-secret-sync
    namespace: platform
