# ServiceAccount, Role, RoleBinding — постоянные ресурсы (НЕ hooks).
# Job — PreSync hook, пересоздаётся при каждой синхронизации.
# SA должен существовать до создания Pod'а Job'а.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-secret-sync
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "5"
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-secret-sync
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "5"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-secret-sync
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: registry-secret-sync
subjects:
  - kind: ServiceAccount
    name: registry-secret-sync
    namespace: platform
