# Secret для доступа к Container Registry TimeWeb
# 
# ПРИМЕЧАНИЕ: Этот файл больше не используется напрямую.
# Секрет автоматически синхронизируется из Vault через Job `registry-secret-sync`.
# 
# Секрет в Vault должен находиться по пути: /v1/kv/data/container-register
# С ключами: REGISTRY_URL, REGISTRY_USERNAME, REGISTRY_PASSWORD
#
# Для ручного создания (если нужно):
# 1. Замените <REGISTRY_USERNAME> и <REGISTRY_PASSWORD> на реальные значения
# 2. Создайте base64 encoded .dockerconfigjson:
#    echo -n '{"auths":{"archpad-cr.registry.twcstorage.ru":{"username":"<USERNAME>","password":"<PASSWORD>","auth":"'$(echo -n '<USERNAME>:<PASSWORD>' | base64)'"}}}' | base64
# 3. Замените <BASE64_ENCODED_DOCKERCONFIGJSON> на полученное значение
#
# ИЛИ создайте Secret вручную через kubectl:
# kubectl create secret docker-registry archpad-registry-secret \
#   --docker-server=archpad-cr.registry.twcstorage.ru \
#   --docker-username=<REGISTRY_USERNAME> \
#   --docker-password=<REGISTRY_PASSWORD> \
#   --namespace=platform

apiVersion: v1
kind: Secret
metadata:
  name: archpad-registry-secret
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "5"
type: kubernetes.io/dockerconfigjson
data:
  # Замените на base64 encoded .dockerconfigjson
  # Формат: {"auths":{"archpad-cr.registry.twcstorage.ru":{"username":"<USERNAME>","password":"<PASSWORD>","auth":"<BASE64(username:password)>"}}}
  # 
  # Для создания используйте:
  # echo -n '{"auths":{"archpad-cr.registry.twcstorage.ru":{"username":"<USERNAME>","password":"<PASSWORD>","auth":"'$(echo -n '<USERNAME>:<PASSWORD>' | base64)'"}}}' | base64
  .dockerconfigjson: <BASE64_ENCODED_DOCKERCONFIGJSON>
