# ==== GraphQL Hasura через Oathkeeper ====
- id: hasura-graphql
  match:
    url: ^https?://[^/]+/graphql/.*
    methods: ["GET", "POST", "OPTIONS"]
  authenticators:
    - handler: oauth2_introspection
  authorizer:
    handler: allow
  mutators:
    - handler: header
      config:
        headers:
          X-Hasura-User-Id: "{{ .Subject }}"
          X-Hasura-Tenant-Ids: "{{ join \",\" .Extra.identity.traits.tenant_ids }}"
          X-Hasura-Roles: "{{ join \",\" .Extra.identity.traits.roles }}"
  upstream:
    url: http://hasura:8080

# ==== Arch-repo-service через Oathkeeper ====
- id: arch-repo-api
  match:
    url: ^https?://[^/]+/rest/.*
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
  authenticators:
    - handler: oauth2_introspection
  authorizer:
    handler: allow
  mutators:
    - handler: header
      config:
        headers:
          X-Archpad-User-Id: "{{ .Subject }}"
          X-Archpad-Tenant-Ids: "{{ join \",\" .Extra.identity.traits.tenant_ids }}"
          X-Archpad-Roles: "{{ join \",\" .Extra.identity.traits.roles }}"
  upstream:
    url: http://arch-repo:3000
