# ==== GraphQL Hasura через Oathkeeper ====
- id: hasura-graphql
  match:
    url: <https|http>://api.192-168-1-119.sslip.io/graphql<(/.*)?>
    methods: ["GET", "POST", "OPTIONS"]
  upstream:
    url: http://hasura:8080
    preserve_host: true
    strip_path: /graphql
  authenticators:
    - handler: oauth2_introspection
  authorizer:
    handler: allow
  mutators:
    - handler: header
      config:
        headers:
          X-Hasura-User-Id: "{{ .Subject }}"
#          X-Hasura-Tenant-Ids: "{{ join \",\" .Extra.identity.metadata_public.tenants }}"
#          X-Hasura-Roles: "{{ join \",\" .Extra.identity.metadata_public.roles }}"
          X-Hasura-Role: "public"
          X-Hasura-Allowed-Roles: "public"

# ==== Arch-repo-service через Oathkeeper ====
- id: arch-repo-api
  match:
    url: <https|http>://api.192-168-1-119.sslip.io/rest<(/.*)>
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
  upstream:
    url: http://arch-repo:3000
    preserve_host: true
    strip_path: /rest
  authenticators:
    - handler: oauth2_introspection
  authorizer:
    handler: allow
  mutators:
    - handler: header
      config:
        headers:
          X-Archpad-User-Id: "{{ .Subject }}"
#          X-Archpad-Tenant-Ids: "{{ join \",\" .Extra.identity.metadata_public.tenants }}"
#          X-Archpad-Roles: "{{ join \",\" .Extra.identity.metadata_public.roles }}"
