# ==== GraphQL Hasura через Oathkeeper ====
- id: hasura-graphql
  match:
    url: <https|http>://api.192-168-1-119.sslip.io/graphql<(/.*)?>
    methods: ["GET", "POST", "OPTIONS"]
  upstream:
    url: http://hasura:8080
    preserve_host: true
    strip_path: /graphql
  authenticators:
    - handler: oauth2_introspection
  authorizer:
    handler: allow
  mutators:
    - handler: header
      config:
        headers:
          X-Hasura-User-Id: "{{ .Subject }}"
#          X-Hasura-Tenant-Ids: "{{ join \",\" .Extra.identity.metadata_public.tenants }}"
#          X-Hasura-Roles: "{{ join \",\" .Extra.identity.metadata_public.roles }}"
          X-Hasura-Role: "public"
          X-Hasura-Allowed-Roles: "public"

# ==== Swagger API документация для arch-repo-service (публичный доступ) ====
- id: arch-repo-api-docs
  match:
    url: <https|http>://api.192-168-1-119.sslip.io/rest/arch-repo-service/api-docs<(/.*)?>
    methods: ["GET", "OPTIONS"]
  upstream:
    url: http://arch-repo:3000
    preserve_host: true
    strip_path: /rest/arch-repo-service
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators: []

- id: arch-repo-api-json
  match:
    url: <https|http>://api.192-168-1-119.sslip.io/rest/arch-repo-service/api-json<(/.*)?>
    methods: ["GET", "OPTIONS"]
  upstream:
    url: http://arch-repo:3000
    preserve_host: true
    strip_path: /rest/arch-repo-service
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators: []

# ==== Arch-repo-service через Oathkeeper (требует авторизации) ====
# Исключаем /api-docs и /api-json из этого правила (они обрабатываются отдельно выше)
# Используем паттерн, который требует наличия пути, но не начинающегося с api-docs или api-json
- id: arch-repo-api
  match:
    url: <https|http>://api.192-168-1-119.sslip.io/rest/arch-repo-service/.+
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
  upstream:
    url: http://arch-repo:3000
    preserve_host: true
    strip_path: /rest/arch-repo-service
  authenticators:
    - handler: oauth2_introspection
  authorizer:
    handler: allow
  mutators:
    - handler: header
      config:
        headers:
          X-Archpad-User-Id: "{{ .Subject }}"
#          X-Archpad-Tenant-Ids: "{{ index .Extra \"tenant_id\" }}"
#          X-Archpad-Roles: "{{ index .Extra \"roles\" }}"
