apiVersion: batch/v1
kind: Job
metadata:
  name: hasura-vault-role
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "46"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      annotations:
        argocd.argoproj.io/hook-weight: "0"
    spec:
      # Используем default ServiceAccount, так как Job не требует специальных прав
      # Job просто делает HTTP запросы к Vault API
      serviceAccountName: default
      restartPolicy: Never
      containers:
        - name: hasura-vault-role
          image: curlimages/curl:latest
          command: ["sh", "-c"]
          args:
            - |
              apk add --no-cache jq
              # Используем ограниченный токен, если доступен, иначе root (для обратной совместимости)
              export VAULT_TOKEN="${VAULT_SETUP_TOKEN:-${VAULT_ROOT_TOKEN:-}}"
              if [ -z "$VAULT_TOKEN" ]; then
                echo "[hasura-vault-role] ERROR: VAULT_SETUP_TOKEN or VAULT_ROOT_TOKEN secret is required"
                echo "[hasura-vault-role] Recommended: Create vault-setup-token secret (see docs/VAULT_SETUP.md)"
                echo "[hasura-vault-role] Fallback: Create vault-root-token secret: kubectl create secret generic vault-root-token -n platform --from-literal=VAULT_ROOT_TOKEN='<your-root-token>'"
                exit 1
              fi
              
              if [ -n "$VAULT_SETUP_TOKEN" ]; then
                echo "[hasura-vault-role] Using limited setup token (recommended)"
              else
                echo "[hasura-vault-role] WARNING: Using root token (not recommended for production)"
                echo "[hasura-vault-role] Please migrate to vault-setup-token (see docs/VAULT_SETUP.md)"
              fi
              sh /vault-role/entrypoint.sh
          env:
            # Используем ограниченный токен вместо root токена
            # Если vault-setup-token не существует, используем root (для обратной совместимости)
            - name: VAULT_SETUP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-setup-token
                  key: VAULT_SETUP_TOKEN
                  optional: true
            - name: VAULT_ROOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-root-token
                  key: VAULT_ROOT_TOKEN
                  optional: true
          volumeMounts:
            - name: vault-role
              mountPath: /vault-role
              readOnly: true
      volumes:
        - name: vault-role
          configMap:
            name: hasura-vault-role
            defaultMode: 0755
  backoffLimit: 3
