apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-timeweb-dns01
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  acme:
    email: admin@archpad.pro
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-timeweb-account-key
    solvers:
      - dns01:
          webhook:
            # ВАЖНО: groupName должен содержать ID вашего кластера (CLUSTER_ID).
            # Примерный паттерн у Timeweb: twcloud-<CLUSTER_ID>
            groupName: twcloud-1067343
            # solverName — имя солвера аддона. Согласно документации TimeWeb должно быть 'twcloud-dns'
            solverName: twcloud-dns
            # config пустой объект (требуется для webhook)
            config: {}