import type { Directory, DirectoryCategory } from '@/@types/directory';

export const mockDirectories: Directory[] = [
  // Architecture Layer
  {
    id: 'dir-arch-style',
    code: 'architecture_style',
    name: 'Архитектурный стиль',
    category: 'architecture',
    items: [
      {
        id: 'as-1',
        code: 'bff',
        name: 'BFF (Backend for Frontend)',
        description: 'Отдельный backend-слой под конкретный UI/клиент для оптимизации API под нужды фронтенда.',
        color: '#22c55e',
        order: 1,
        relations: [
          {
            id: 'rel-1',
            sourceDirectoryName: 'Архитектурный стиль',
            sourceItemId: 'as-1',
            sourceItemName: 'BFF (Backend for Frontend)',
            targetDirectoryName: 'Состояние компонента',
            targetItemId: 'cs-2',
            targetItemName: 'Продакшн',
            relationType: 'используется_в',
          },
          {
            id: 'rel-2',
            sourceDirectoryName: 'Архитектурный стиль',
            sourceItemId: 'as-1',
            sourceItemName: 'BFF (Backend for Frontend)',
            targetDirectoryName: 'Уровень критичности',
            targetItemId: 'cl-2',
            targetItemName: 'Средний',
            relationType: 'имеет_критичность',
          },
        ],
      },
      {
        id: 'as-2',
        code: 'cqrs_es',
        name: 'CQRS + Event Sourcing',
        description: 'Разделение моделей чтения/записи и хранение состояния как событий, повышает гибкость, но даёт дуализм/сложность.',
        color: '#3b82f6',
        order: 2,
        relations: [
          {
            id: 'rel-3',
            sourceDirectoryName: 'Архитектурный стиль',
            sourceItemId: 'as-2',
            sourceItemName: 'CQRS + Event Sourcing',
            targetDirectoryName: 'Уровень критичности',
            targetItemId: 'cl-3',
            targetItemName: 'Высокий',
            relationType: 'имеет_критичность',
          },
        ],
      },
      {
        id: 'as-3',
        code: 'clean_architecture',
        name: 'Clean Architecture',
        description: 'Domain-centric подход с изоляцией бизнес-логики от frameworks.',
        color: '#8b5cf6',
        order: 3,
      },
      {
        id: 'as-4',
        code: 'soa',
        name: 'SOA',
        description: 'Сервис-ориентированная архитектура с выделением ИТ-сервисов и контрактов.',
        color: '#f59e0b',
        order: 4,
      },
      {
        id: 'as-5',
        code: 'serverless',
        name: 'Serverless',
        description: 'Функции/микросервисы без управления инфраструктурой, подход для event-driven нагрузки.',
        color: '#ec4899',
        order: 5,
      },
      {
        id: 'as-6',
        code: 'eda_streaming',
        name: 'Streaming-first',
        description: 'Потоковые данные и стриминг-платформы — основной способ интеграции и обработки.',
        color: '#06b6d4',
        order: 6,
      },
      {
        id: 'as-7',
        code: 'hexagonal',
        name: 'Hexagonal (Ports & Adapters)',
        description: 'Домен в центре, интеграция через порты/адаптеры, изолирует бизнес-логику от внешних систем.',
        color: '#14b8a6',
        order: 7,
      },
      {
        id: 'as-8',
        code: 'microservices',
        name: 'Microservices',
        description: 'Набор автономных сервисов, развёртываемых независимо, масштабируемость и гибкость.',
        color: '#a855f7',
        order: 8,
        relations: [
          {
            id: 'rel-4',
            sourceDirectoryName: 'Архитектурный стиль',
            sourceItemId: 'as-8',
            sourceItemName: 'Microservices',
            targetDirectoryName: 'Состояние компонента',
            targetItemId: 'cs-2',
            targetItemName: 'Продакшн',
            relationType: 'используется_в',
          },
          {
            id: 'rel-5',
            sourceDirectoryName: 'Архитектурный стиль',
            sourceItemId: 'as-8',
            sourceItemName: 'Microservices',
            targetDirectoryName: 'Уровень критичности',
            targetItemId: 'cl-4',
            targetItemName: 'Критический',
            relationType: 'имеет_критичность',
          },
          {
            id: 'rel-6',
            sourceDirectoryName: 'Архитектурный стиль',
            sourceItemId: 'as-8',
            sourceItemName: 'Microservices',
            targetDirectoryName: 'Способ обработки отказов',
            targetItemId: 'dt-1',
            targetItemName: 'Circuit Breaker',
            relationType: 'использует_паттерн',
          },
        ],
      },
      {
        id: 'as-9',
        code: 'modular_monolith',
        name: 'Модульный монолит',
        description: 'Монолит с явными модулями/границами (bounded contexts), допускающий постепенную декомпозицию.',
        color: '#ef4444',
        order: 9,
      },
    ],
  },
  {
    id: 'dir-component-state',
    code: 'component_state',
    name: 'Состояние компонента',
    category: 'architecture',
    items: [
      {
        id: 'cs-1',
        code: 'development',
        name: 'Разработка',
        description: 'Компонент находится в разработке',
        color: '#3b82f6',
        order: 1,
      },
      {
        id: 'cs-2',
        code: 'production',
        name: 'Продакшн',
        description: 'Компонент в продуктивной эксплуатации',
        color: '#22c55e',
        order: 2,
      },
      {
        id: 'cs-3',
        code: 'deprecated',
        name: 'Устарел',
        description: 'Компонент устарел и будет выведен из эксплуатации',
        color: '#f59e0b',
        order: 3,
      },
      {
        id: 'cs-4',
        code: 'retired',
        name: 'Выведен',
        description: 'Компонент выведен из эксплуатации',
        color: '#6b7280',
        order: 4,
      },
    ],
  },
  {
    id: 'dir-critical-level',
    code: 'critical_level',
    name: 'Уровень критичности',
    category: 'architecture',
    items: [
      {
        id: 'cl-1',
        code: 'low',
        name: 'Низкий',
        description: 'Некритичный компонент',
        color: '#22c55e',
        order: 1,
      },
      {
        id: 'cl-2',
        code: 'medium',
        name: 'Средний',
        description: 'Средняя критичность',
        color: '#f59e0b',
        order: 2,
      },
      {
        id: 'cl-3',
        code: 'high',
        name: 'Высокий',
        description: 'Высокая критичность',
        color: '#ef4444',
        order: 3,
      },
      {
        id: 'cl-4',
        code: 'critical',
        name: 'Критический',
        description: 'Критически важный компонент',
        color: '#dc2626',
        order: 4,
      },
    ],
  },
  {
    id: 'dir-license-type',
    code: 'license_type',
    name: 'Тип лицензии',
    category: 'classification',
    items: [
      {
        id: 'lt-1',
        code: 'commercial',
        name: 'Коммерческая',
        description: 'Коммерческая лицензия',
        order: 1,
      },
      {
        id: 'lt-2',
        code: 'opensource',
        name: 'Open Source',
        description: 'Открытая лицензия',
        order: 2,
      },
      {
        id: 'lt-3',
        code: 'proprietary',
        name: 'Проприетарная',
        description: 'Проприетарная лицензия',
        order: 3,
      },
      {
        id: 'lt-4',
        code: 'freeware',
        name: 'Freeware',
        description: 'Бесплатное ПО',
        order: 4,
      },
    ],
  },
  {
    id: 'dir-deployment-type',
    code: 'deployment_type',
    name: 'Способ обработки отказов',
    category: 'architecture',
    items: [
      {
        id: 'dt-1',
        code: 'circuit_breaker',
        name: 'Circuit Breaker',
        description: 'Предохранитель для защиты от каскадных сбоев',
        order: 1,
      },
      {
        id: 'dt-2',
        code: 'retry',
        name: 'Retry',
        description: 'Повторные попытки при сбое',
        order: 2,
      },
      {
        id: 'dt-3',
        code: 'fallback',
        name: 'Fallback',
        description: 'Запасной вариант при недоступности основного',
        order: 3,
      },
    ],
  },
];

export const directoryCategories: DirectoryCategory[] = [
  {
    id: 'cat-arch',
    name: 'Архитектурные слои',
    directories: mockDirectories.filter(d => d.category === 'architecture'),
  },
  {
    id: 'cat-class',
    name: 'Классификаторы',
    directories: mockDirectories.filter(d => d.category === 'classification'),
  },
  {
    id: 'cat-ref',
    name: 'Справочники',
    directories: mockDirectories.filter(d => d.category === 'reference'),
  },
];

export function getDirectoryById(id: string): Directory | undefined {
  return mockDirectories.find(d => d.id === id);
}

export function getDirectoryByCode(code: string): Directory | undefined {
  return mockDirectories.find(d => d.code === code);
}