server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 168h

# Enable metrics-generator so Grafana Traces Drilldown (TraceQL metrics) works.
# Without it Tempo returns "error finding generators: empty ring".
metrics_generator:
  ring:
    kvstore:
      store: inmemory
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  processor:
    service_graphs:
      max_items: 10000
    span_metrics:
      dimensions: []
  storage:
    path: /var/tempo/generator/wal

overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal


