apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: secure
  annotations:
    argocd.argoproj.io/sync-wave: "70"
spec:
  redirectScheme:
    scheme: https
    permanent: true
