apiVersion: v1
kind: Service
metadata:
  name: oathkeeper
  namespace: secure
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  type: ClusterIP
  ports:
    - name: proxy
      port: 4455
      targetPort: proxy
      protocol: TCP
    - name: api
      port: 4456
      targetPort: api
      protocol: TCP
  selector:
    app: oathkeeper
